openapi: 3.0.3
info:
  title: Odpowiedniki leków
  version: 1.0.0
paths:
  #  /:
  #    get:
  #      summary: Kod źródłowy strony internetowej.
  #      responses:
  #        "200":
  #          description: Pobieranie strony udane.
  #  /search:
  #    get:
  #      summary: Wyszukiwanie leku w bazie danych.
  #      parameters:
  #        - in: query 
  #          name: q
  #          description: Fraza do wyszukiwania.
  #          required: true
  #          schema:
  #            type: string
  #        - in: query 
  #          name: p 
  #          description: Numer strony wyszukiwania (w stronicowaniu wyników).
  #          required: false
  #          schema:
  #            type: integer
  #            default: 1
  #      responses:
  #        "200":
  #          description: Kod HTML na zapytanie przekazane w parametrach.
  /api/groups/{group_id}:
    get:
      summary: Lista odpowiedników podanej grupy.
      parameters:
        - in: path
          name: group_id
          description: Numer identyfikacyjny grupy odpowiedników.
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Pobieranie listy powiodło się.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Drug"
        "404":
          description: Lista o podanym id nie została znaleziona.
  /api/details/{id}:
    get:
      summary: Szczegółowe informacje o leku o podanym id.
      parameters:
        - in: path
          name: id
          description: Numer identyfikacyjny leku. 
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Pobieranie informacji o leku powiodło się.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Drug'
        "404":
          description: Lek o podanym id nie została znaleziony.

  /api/selection/{ean}:
    get:
      summary: Szczegółowe informacje o leku o kodzie EAN.
      parameters:
        - in: path
          name: ean
          description: Kod EAN leku do sprawdzenia.
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Pobieranie informacji o leku powiodło się.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Drug"
                  
        "404":
          description: Lek o podanym EAN nie został znaleziony.
  /api/search:
    get:
      summary: Wyszukiwanie leków.
      parameters:
        - in: query 
          name: q
          description: Fraza do wyszukiwania.
          required: true
          schema:
            type: string
        - in: query 
          name: p 
          description: Numer strony wyszukiwania (w stronicowaniu wyników).
          required: false
          schema:
            type: integer
            default: 1
      responses:
        "200":
          description: Wyszukiwanie udane.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Drug"
        "400":
          description: Zły numer strony.
components:
  schemas:
    Drug:
      type: object
      properties:
        id:
          type: integer
          format: i64
          example: 2512
        name:
          type: string
          description: Nazwa produktu.
          example: Amoksiklav
        ean:
          type: string
          description: Kod EAN.
          example: 123456789
        refound:
          type: string
          description: Poziom refundacji.
          example: 30
        price:
          type: number
          description: Cena, jaką należy zapłacić za opakowanie.
          example: 30.99
        amount:
          type: number
          description: Ilość jednostek produktu w jednym opakowaniu.
          example: 5
        amount_unit:
          type:
            - string
            - 'null'
          description: Jednostka, w jakiej zostało podane pole 'amount'.
          example: 'null'
        group_id:
          type:
            - integer
            - 'null'
          description: Id grupy odpowiedników leków
          example: '5'
