{
  "swagger": "2.0",
  "info": {
    "title": "Odpowiedniki leków"
  },
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/search": {
      "post": {
        "summary": "Wykonaj proces wyszukiwania leku.",
        "parameters": [
          {
            "name": "phrase",
            "in": "query",
            "description": "Fraza wpisana przez użytkownika.",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Lista wynikowa leków.",
            "schema": {
              "$ref": "#/definitions/Lista_leków"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Lek": {
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64",
          "description": "Id leku jednoznacznie go identyfikujące."
        }
      }
    },
    "Lista_leków": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Lek"
      }
    }
  }
}
